import React from 'react';
import { ResultReport } from './ResultReport';
import { InterviewSession } from '../types';

interface SampleTranscriptProps {
  onStartNew: () => void;
}

const SAMPLE_MOCK_SESSION: InterviewSession = {
  id: 'mock-sample-001',
  candidateName: 'John Doe',
  role: 'Java Developer',
  experience: 'Mid-Level',
  createdAt: new Date().toISOString(),
  timerSecondsPerQuestion: 180,
  currentQuestionIndex: 5,
  status: 'completed',
  questions: [
    {
      id: 1,
      question: 'What is the JVM and how does it execute Java bytecode?',
      difficulty: 'Easy',
      focus: 'Core Java Architecture'
    },
    {
      id: 2,
      question: 'Explain the internal working difference between ArrayList and LinkedList in Java collections.',
      difficulty: 'Medium',
      focus: 'Data Structures & Performance'
    },
    {
      id: 3,
      question: 'How does multithreading work in Java? Explain race conditions and synchronization mechanisms.',
      difficulty: 'Medium',
      focus: 'Concurrency & Thread Safety'
    },
    {
      id: 4,
      question: 'What happens when two threads update the same object concurrently? How do synchronized blocks or ReentrantLocks prevent memory inconsistencies?',
      difficulty: 'Hard',
      focus: 'Advanced Concurrency & Memory Model'
    },
    {
      id: 5,
      question: 'Design an Employee Management REST API using Spring Boot. Explain layer architecture, exception handling, and database indexing strategies.',
      difficulty: 'Scenario Based',
      focus: 'System Architecture & Design'
    }
  ],
  evaluations: [
    {
      questionNumber: 1,
      question: 'What is the JVM and how does it execute Java bytecode?',
      difficulty: 'Easy',
      candidateAnswer: 'JVM stands for Java Virtual Machine. It loads .class bytecode files generated by javac compiler and converts them into native machine code using JIT compilation or interpreter so it can run on any platform.',
      score: 9,
      feedback: 'Excellent explanation of bytecode loading, JIT compilation, and cross-platform execution architecture.',
      correctAnswer: 'The Java Virtual Machine (JVM) is an abstract computing machine that provides a runtime execution environment. The JVM architecture comprises ClassLoader, Memory Management (Heap, Stack, Method Area), Execution Engine (Interpreter + JIT Compiler), and Native Interface.',
      topicsToImprove: ['Garbage Collection algorithms (G1, ZGC)']
    },
    {
      questionNumber: 2,
      question: 'Explain the internal working difference between ArrayList and LinkedList in Java collections.',
      difficulty: 'Medium',
      candidateAnswer: 'ArrayList is backed by a dynamically resizing array, so index lookup is O(1) time. LinkedList uses doubly-linked nodes structure, so index lookup is O(N) but insertion in the middle is faster once node position is found.',
      score: 8,
      feedback: 'Good overview of Big-O complexity and internal underlying arrays versus linked nodes.',
      correctAnswer: 'ArrayList implements RandomAccess backed by a dynamic contiguous array. Index lookup is O(1), but middle insertion/deletion requires array copying (O(N)). LinkedList uses doubly-linked nodes; memory overhead is higher per element due to node pointer references, and lookup requires traversal (O(N)).',
      topicsToImprove: ['Memory allocation overhead per node in LinkedList']
    },
    {
      questionNumber: 3,
      question: 'How does multithreading work in Java? Explain race conditions and synchronization mechanisms.',
      difficulty: 'Medium',
      candidateAnswer: 'Multithreading allows multiple threads to execute concurrently inside the JVM. A race condition occurs when multiple threads modify shared state without proper locks, leading to unpredictable data. We use synchronized keywords or locks.',
      score: 8,
      feedback: 'Clear definition of race condition and thread synchronization concepts.',
      correctAnswer: 'Java multithreading executes concurrent paths using JVM thread mapping. A race condition happens when shared mutable state is accessed concurrently without mutual exclusion. Java provides synchronization via synchronized blocks, volatile keywords (visibility), ReentrantLock, and Atomic classes in java.util.concurrent.',
      topicsToImprove: ['Volatile keyword vs Synchronized locks']
    },
    {
      questionNumber: 4,
      question: 'What happens when two threads update the same object concurrently? How do synchronized blocks or ReentrantLocks prevent memory inconsistencies?',
      difficulty: 'Hard',
      candidateAnswer: 'If two threads write to the same object at once, thread context switches can interleave operations or read stale CPU cached values, causing lost updates. Synchronized locks memory monitors so only one thread enters the synchronized block, forcing cache flushing to main memory.',
      score: 7,
      feedback: 'Very solid answer mentioning CPU caches and monitors, though could elaborate on lock fairness and tryLock timeouts.',
      correctAnswer: 'Concurrent updates without synchronization cause thread race conditions, dirty reads, or corrupted memory states due to thread-local CPU cache invisibility (Java Memory Model - JMM). Synchronized acquires an intrinsic object monitor. ReentrantLock offers advanced capabilities such as explicit lock polling (tryLock), fairness policies, and Condition variables.',
      topicsToImprove: ['Java Memory Model (JMM) happens-before guarantee', 'ReentrantLock Condition variables']
    },
    {
      questionNumber: 5,
      question: 'Design an Employee Management REST API using Spring Boot. Explain layer architecture, exception handling, and database indexing strategies.',
      difficulty: 'Scenario Based',
      candidateAnswer: 'I would build a standard multi-layer architecture: Controller (@RestController) -> Service (@Service) -> Repository (@Repository / Spring Data JPA). For exceptions, use @ControllerAdvice with @ExceptionHandler to return structured JSON errors. For database, index employee_id and department_id for high-frequency search queries.',
      score: 8,
      feedback: 'Great pragmatic system design response covering controllers, global exception advice, and database indexing.',
      correctAnswer: 'Architecture: Controller layer handles HTTP routing & DTO validation (@Valid); Service layer encapsulates business logic & @Transactional management; Repository uses Spring Data JPA. Exception Handling: Global @RestControllerAdvice handles custom exceptions returning RFC 7807 ProblemDetails JSON. Database Indexing: Create B-Tree indexes on filtered/sorted columns (department_id, email), and compound indexes for composite queries.',
      topicsToImprove: ['DTO mapping vs Entity exposure', 'Database connection pooling tuning']
    }
  ],
  finalReport: {
    overallScore: 40,
    maxScore: 50,
    percentage: 80,
    status: 'Selected',
    recommendation: 'Suitable for Junior/Mid-Level Java Developer — Candidate demonstrated strong core technical competence.',
    strengths: [
      'Solid understanding of JVM internals and bytecode execution',
      'Strong grasp of Java Collections and Big-O trade-offs',
      'Good practical knowledge of Spring Boot REST API design and exception handling'
    ],
    weaknesses: [
      'Slightly surface-level explanation of Java Memory Model (JMM) happens-before rules',
      'Could elaborate more on ReentrantLock advanced features (tryLock, Conditions)'
    ],
    topicsToImprove: [
      'Java Memory Model (JMM) & volatile memory visibility guarantees',
      'Advanced Concurrency tools (ReentrantLock, Semaphore, CountDownLatch)',
      'Garbage Collection tuning (G1GC vs ZGC)'
    ],
    learningResources: [
      {
        title: 'Java Concurrency in Practice by Brian Goetz',
        type: 'Book',
        description: 'The definitive guide to multithreading, memory model, and concurrent collections in Java.'
      },
      {
        title: 'Spring Boot REST API Architecture & Best Practices',
        type: 'Documentation / Tutorial',
        description: 'Official Spring guides on REST exception handling, validation, and database performance.'
      }
    ],
    summary: 'John demonstrated strong technical competence across Java fundamentals, object-oriented concepts, and Spring Boot backend engineering. His performance in scenario-based architectural questions was impressive with a score of 40/50.'
  }
};

export const SampleTranscript: React.FC<SampleTranscriptProps> = ({ onStartNew }) => {
  return (
    <div className="space-y-4">
      <div className="max-w-5xl mx-auto px-4 pt-6">
        <div className="p-4 rounded-xl bg-cyan-900/10 border border-cyan-200 text-cyan-900 text-xs sm:text-sm flex items-center justify-between">
          <p>
            <strong>Sample Showcase Report:</strong> This pre-evaluated mock transcript demonstrates the 5-question evaluation flow for a <strong>Java Developer</strong> role.
          </p>
          <button
            onClick={onStartNew}
            className="px-3 py-1.5 rounded-lg bg-indigo-600 text-white font-bold text-xs hover:bg-indigo-700 transition-all shrink-0 ml-4"
          >
            Try Interactive Interview
          </button>
        </div>
      </div>

      <ResultReport
        candidateName={SAMPLE_MOCK_SESSION.candidateName}
        role={SAMPLE_MOCK_SESSION.role}
        experience={SAMPLE_MOCK_SESSION.experience}
        evaluations={SAMPLE_MOCK_SESSION.evaluations}
        report={SAMPLE_MOCK_SESSION.finalReport!}
        onRetake={onStartNew}
        sessionId={SAMPLE_MOCK_SESSION.id}
      />
    </div>
  );
};
