import fs from 'fs';
import path from 'path';
import { HistoryRecord, InterviewSession } from '../types';

const DATA_DIR = path.join(process.cwd(), 'data');
const OUTPUTS_DIR = path.join(process.cwd(), 'outputs');
const DB_FILE = path.join(DATA_DIR, 'interview.db.json');
const TRANSCRIPT_FILE = path.join(OUTPUTS_DIR, 'transcript.json');

// Ensure directories exist
function ensureDirectories() {
  if (!fs.existsSync(DATA_DIR)) {
    fs.mkdirSync(DATA_DIR, { recursive: true });
  }
  if (!fs.existsSync(OUTPUTS_DIR)) {
    fs.mkdirSync(OUTPUTS_DIR, { recursive: true });
  }
  if (!fs.existsSync(DB_FILE)) {
    fs.writeFileSync(DB_FILE, JSON.stringify([], null, 2), 'utf-8');
  }
}

// Initial Sample Data for pre-populated history
const SAMPLE_MOCK_SESSION: InterviewSession = {
  id: 'mock-sample-001',
  candidateName: 'John Doe',
  role: 'Java Developer',
  experience: 'Mid-Level',
  createdAt: new Date().toISOString(),
  timerSecondsPerQuestion: 180,
  currentQuestionIndex: 5,
  status: 'completed',
  questions: [
    {
      id: 1,
      question: 'What is the JVM and how does it execute Java bytecode?',
      difficulty: 'Easy',
      focus: 'Core Java Architecture'
    },
    {
      id: 2,
      question: 'Explain the internal working difference between ArrayList and LinkedList in Java collections.',
      difficulty: 'Medium',
      focus: 'Data Structures & Performance'
    },
    {
      id: 3,
      question: 'How does multithreading work in Java? Explain race conditions and synchronization mechanisms.',
      difficulty: 'Medium',
      focus: 'Concurrency & Thread Safety'
    },
    {
      id: 4,
      question: 'What happens when two threads update the same object concurrently? How do synchronized blocks or ReentrantLocks prevent memory inconsistencies?',
      difficulty: 'Hard',
      focus: 'Advanced Concurrency & Memory Model'
    },
    {
      id: 5,
      question: 'Design an Employee Management REST API using Spring Boot. Explain layer architecture, exception handling, and database indexing strategies.',
      difficulty: 'Scenario Based',
      focus: 'System Architecture & Design'
    }
  ],
  evaluations: [
    {
      questionNumber: 1,
      question: 'What is the JVM and how does it execute Java bytecode?',
      difficulty: 'Easy',
      candidateAnswer: 'JVM stands for Java Virtual Machine. It loads .class bytecode files generated by javac compiler and converts them into native machine code using JIT compilation or interpreter so it can run on any platform.',
      score: 9,
      feedback: 'Excellent explanation of bytecode loading, JIT compilation, and cross-platform architecture.',
      correctAnswer: 'The Java Virtual Machine (JVM) is an abstract computing machine that provides a runtime environment to execute Java bytecode. The JVM architecture includes ClassLoader, Memory Area (Heap, Stack, Method Area), Execution Engine (Interpreter + JIT Compiler), and Native Interface. Bytecode (.class) is loaded, verified, and dynamically translated into machine instruction.',
      topicsToImprove: ['Garbage Collection algorithms']
    },
    {
      questionNumber: 2,
      question: 'Explain the internal working difference between ArrayList and LinkedList in Java collections.',
      difficulty: 'Medium',
      candidateAnswer: 'ArrayList is backed by a dynamically resizing array, so positional access by index is O(1) time. LinkedList uses a doubly-linked list nodes structure, so lookup is O(N) but additions/deletions in the middle are faster once node position is found.',
      score: 8,
      feedback: 'Good overview of Big-O complexity and internal underlying arrays versus linked nodes.',
      correctAnswer: 'ArrayList implements RandomAccess using a dynamic array. Index lookup is O(1), but insertion/deletion requires array copying (O(N)). LinkedList uses doubly-linked nodes; memory overhead is higher per element due to node pointers, and lookup requires traversal (O(N)), but node link updates are O(1).',
      topicsToImprove: ['Memory overhead per node in LinkedList']
    },
    {
      questionNumber: 3,
      question: 'How does multithreading work in Java? Explain race conditions and synchronization mechanisms.',
      difficulty: 'Medium',
      candidateAnswer: 'Multithreading lets multiple threads execute concurrently within the JVM. A race condition occurs when multiple threads modify shared state without proper locks, leading to unpredictable data. We use synchronized keywords or locks.',
      score: 8,
      feedback: 'Clear definition of race condition and thread synchronization concepts.',
      correctAnswer: 'Java multithreading executes concurrent paths using JVM thread mapping. A race condition happens when shared mutable state is accessed concurrently without mutual exclusion. Java provides synchronization via synchronized blocks, volatile keywords (visibility), ReentrantLock, and Atomic classes in java.util.concurrent.',
      topicsToImprove: ['Volatile keyword vs Synchronized']
    },
    {
      questionNumber: 4,
      question: 'What happens when two threads update the same object concurrently? How do synchronized blocks or ReentrantLocks prevent memory inconsistencies?',
      difficulty: 'Hard',
      candidateAnswer: 'If two threads write to the same object at once, thread context switches can interleave operations or read stale CPU cached values, causing lost updates. Synchronized locks memory monitors so only one thread enters the synchronized block, forcing cache flushing to main memory.',
      score: 7,
      feedback: 'Very solid answer mentioning CPU caches and monitors, though could elaborate on lock fairness and tryLock timeouts.',
      correctAnswer: 'Concurrent updates without synchronization cause thread race conditions, dirty reads, or corrupted memory states due to thread-local CPU cache invisibility (Java Memory Model - JMM). Synchronized acquires an intrinsic object monitor (monitorenter/monitorexit). ReentrantLock offers advanced capabilities such as explicit lock polling (tryLock), fairness policies, and multiple Condition variables.',
      topicsToImprove: ['Java Memory Model (JMM) happens-before guarantee', 'ReentrantLock Condition variables']
    },
    {
      questionNumber: 5,
      question: 'Design an Employee Management REST API using Spring Boot. Explain layer architecture, exception handling, and database indexing strategies.',
      difficulty: 'Scenario Based',
      candidateAnswer: 'I would build a standard multi-layer architecture: Controller (@RestController) -> Service (@Service) -> Repository (@Repository / Spring Data JPA). For exceptions, use @ControllerAdvice with @ExceptionHandler to return structured JSON errors. For database, index employee_id and department_id for high-frequency search queries.',
      score: 8,
      feedback: 'Great pragmatic system design response covering controllers, global exception advice, and database indexing.',
      correctAnswer: 'Architecture: Controller layer handles HTTP routing & DTO validation (@Valid); Service layer encapsulates business logic & @Transactional management; Repository uses Spring Data JPA with entity mappings. Exception Handling: Global @RestControllerAdvice handles custom exceptions returning RFC 7807 ProblemDetails JSON. Database Indexing: Create B-Tree indexes on filtered/sorted columns (e.g., department_id, email, status), and compound indexes for composite queries.',
      topicsToImprove: ['DTO mapping vs Entity exposure', 'Database connection pooling tuning']
    }
  ],
  finalReport: {
    overallScore: 40,
    maxScore: 50,
    percentage: 80,
    status: 'Selected',
    recommendation: 'Strong Candidate — Recommended for Mid-Level Java Developer Role.',
    strengths: [
      'Solid understanding of JVM internals and bytecode execution',
      'Strong grasp of Java Collections and Big-O trade-offs',
      'Good practical knowledge of Spring Boot REST API design and exception handling'
    ],
    weaknesses: [
      'Slightly surface-level explanation of Java Memory Model (JMM) happens-before rules',
      'Could elaborate more on ReentrantLock advanced features (tryLock, Conditions)'
    ],
    topicsToImprove: [
      'Java Memory Model (JMM) & volatile memory visibility guarantees',
      'Advanced Concurrency tools (ReentrantLock, Semaphore, CountDownLatch)',
      'Garbage Collection tuning (G1GC vs ZGC)'
    ],
    learningResources: [
      {
        title: 'Java Concurrency in Practice by Brian Goetz',
        type: 'Book',
        description: 'The definitive guide to multithreading, memory model, and concurrent collections in Java.'
      },
      {
        title: 'Spring Boot REST API Architecture & Best Practices',
        type: 'Documentation / Tutorial',
        description: 'Official Spring guides on REST exception handling, validation, and database performance.'
      }
    ],
    summary: 'John demonstrated strong core technical competence across Java fundamentals, object-oriented concepts, and Spring Boot backend engineering. His performance in scenario-based architectural questions was impressive.'
  }
};

function readRecordsFromDisk(): HistoryRecord[] {
  ensureDirectories();
  try {
    const raw = fs.readFileSync(DB_FILE, 'utf-8');
    const records: HistoryRecord[] = JSON.parse(raw || '[]');
    return Array.isArray(records) ? records : [];
  } catch (err) {
    console.error('Error reading sessions database file:', err);
    return [];
  }
}

export function getAllSessions(): HistoryRecord[] {
  ensureDirectories();
  let records = readRecordsFromDisk();
  
  // If empty, initialize with sample record for demonstration
  if (records.length === 0) {
    const sampleRecord: HistoryRecord = {
      id: SAMPLE_MOCK_SESSION.id,
      candidateName: SAMPLE_MOCK_SESSION.candidateName,
      role: SAMPLE_MOCK_SESSION.role,
      experience: SAMPLE_MOCK_SESSION.experience,
      overallScore: SAMPLE_MOCK_SESSION.finalReport?.overallScore || 40,
      maxScore: 50,
      status: SAMPLE_MOCK_SESSION.finalReport?.status || 'Selected',
      recommendation: SAMPLE_MOCK_SESSION.finalReport?.recommendation || 'Selected',
      createdAt: SAMPLE_MOCK_SESSION.createdAt,
      questionsCount: 5,
      data: SAMPLE_MOCK_SESSION
    };

    records = [sampleRecord];
    try {
      fs.writeFileSync(DB_FILE, JSON.stringify(records, null, 2), 'utf-8');
      
      const transcriptOutput = {
        candidate_info: {
          id: SAMPLE_MOCK_SESSION.id,
          name: SAMPLE_MOCK_SESSION.candidateName,
          role: SAMPLE_MOCK_SESSION.role,
          experience: SAMPLE_MOCK_SESSION.experience,
          date: SAMPLE_MOCK_SESSION.createdAt
        },
        questions_and_evaluations: SAMPLE_MOCK_SESSION.evaluations,
        final_report: SAMPLE_MOCK_SESSION.finalReport || null
      };
      fs.writeFileSync(TRANSCRIPT_FILE, JSON.stringify(transcriptOutput, null, 2), 'utf-8');
    } catch (err) {
      console.error('Error initializing sample session on disk:', err);
    }
  }
  
  return records;
}

export function saveSession(session: InterviewSession): HistoryRecord {
  ensureDirectories();
  const records = readRecordsFromDisk();

  const record: HistoryRecord = {
    id: session.id,
    candidateName: session.candidateName,
    role: session.role,
    experience: session.experience,
    overallScore: session.finalReport?.overallScore || 0,
    maxScore: session.finalReport?.maxScore || 50,
    status: session.finalReport?.status || 'In Progress',
    recommendation: session.finalReport?.recommendation || 'Pending',
    createdAt: session.createdAt || new Date().toISOString(),
    questionsCount: session.questions.length,
    data: session
  };

  const existingIdx = records.findIndex((r) => r.id === session.id);
  if (existingIdx >= 0) {
    records[existingIdx] = record;
  } else {
    records.unshift(record);
  }

  // Write to SQLite JSON DB
  fs.writeFileSync(DB_FILE, JSON.stringify(records, null, 2), 'utf-8');

  // Also write the latest session transcript to transcript.json as requested in outputs/transcript.json deliverable
  try {
    const transcriptOutput = {
      candidate_info: {
        id: session.id,
        name: session.candidateName,
        role: session.role,
        experience: session.experience,
        date: session.createdAt
      },
      questions_and_evaluations: session.evaluations,
      final_report: session.finalReport || null
    };
    fs.writeFileSync(TRANSCRIPT_FILE, JSON.stringify(transcriptOutput, null, 2), 'utf-8');
  } catch (err) {
    console.error('Error writing transcript.json output:', err);
  }

  return record;
}

export function getSessionById(id: string): HistoryRecord | undefined {
  const records = getAllSessions();
  return records.find((r) => r.id === id);
}

export function deleteSessionById(id: string): boolean {
  ensureDirectories();
  const records = getAllSessions();
  const filtered = records.filter((r) => r.id !== id);
  if (filtered.length !== records.length) {
    fs.writeFileSync(DB_FILE, JSON.stringify(filtered, null, 2), 'utf-8');
    return true;
  }
  return false;
}
